import type { Node, Edge } from '@xyflow/react'
import type { NodeData, AgentKind } from '../types/agent'

/** Generate a Python variable name from a display name */
function pyVar(name: string): string {
  return name.trim().replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '').toLowerCase() || 'agent'
}

/** Topological sort — returns node IDs leaves-first */
function topoSort(nodes: Node<NodeData>[], subAgentEdges: Edge[]): string[] {
  const children: Record<string, string[]> = {}
  const parents: Record<string, string[]> = {}
  for (const n of nodes) {
    children[n.id] = []
    parents[n.id] = []
  }
  for (const e of subAgentEdges) {
    children[e.source].push(e.target)
    parents[e.target].push(e.source)
  }
  const visited = new Set<string>()
  const order: string[] = []
  function visit(id: string) {
    if (visited.has(id)) return
    visited.add(id)
    for (const child of children[id]) visit(child)
    order.push(id)
  }
  for (const n of nodes) visit(n.id)
  // order is reverse-topological (roots first) — we want leaves first
  return order.reverse()
}

export function generatePythonCode(nodes: Node<NodeData>[], edges: Edge[]): string {
  if (nodes.length === 0) return '# Empty design — add some nodes first\n'

  const subAgentEdges = edges.filter((e) => e.data?.kind === 'sub_agent' || !e.data?.kind)
  const toolEdges = edges.filter((e) => e.data?.kind === 'tool')

  // Map: agentId → [toolId, ...]
  const agentTools: Record<string, string[]> = {}
  for (const e of toolEdges) {
    if (!agentTools[e.source]) agentTools[e.source] = []
    agentTools[e.source].push(e.target)
  }

  // Map: parentId → [childId, ...]
  const subAgentChildren: Record<string, string[]> = {}
  for (const e of subAgentEdges) {
    if (!subAgentChildren[e.source]) subAgentChildren[e.source] = []
    subAgentChildren[e.source].push(e.target)
  }

  // Identify root: workflow agent with no incoming sub_agent edges
  const childIds = new Set(subAgentEdges.map((e) => e.target))
  const workflowKinds: AgentKind[] = ['SequentialAgent', 'ParallelAgent', 'LoopAgent', 'LlmAgent']
  const roots = nodes.filter(
    (n) => workflowKinds.includes(n.data.kind) && !childIds.has(n.id),
  )

  const nodeById: Record<string, Node<NodeData>> = {}
  for (const n of nodes) nodeById[n.id] = n

  // Sort: leaves first so every variable is defined before it's referenced
  const sortedIds = topoSort(nodes, subAgentEdges)

  // Collect which ADK kinds are actually used
  const usedKinds = new Set(nodes.map((n) => n.data.kind))
  const hasTool = usedKinds.has('Tool')
  const hasMcp = usedKinds.has('McpToolset')

  const lines: string[] = []

  // ── Imports ──────────────────────────────────────────────────────────────
  lines.push('# Generated by ADK Agent Designer')
  lines.push('')
  if (usedKinds.has('LlmAgent')) {
    lines.push('from google.adk.agents.llm_agent import LlmAgent')
  }
  if (usedKinds.has('SequentialAgent')) {
    lines.push('from google.adk.agents.sequential_agent import SequentialAgent')
  }
  if (usedKinds.has('ParallelAgent')) {
    lines.push('from google.adk.agents.parallel_agent import ParallelAgent')
  }
  if (usedKinds.has('LoopAgent')) {
    lines.push('from google.adk.agents.loop_agent import LoopAgent')
  }
  if (hasMcp) {
    lines.push('from google.adk.tools.mcp_tool import McpToolset')
    lines.push(
      'from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams',
    )
    lines.push('from mcp import StdioServerParameters')
  }
  if (hasTool) {
    lines.push('from google.adk.tools import ToolContext  # noqa: F401 — available if needed')
  }
  lines.push('')

  // ── Tool function definitions ─────────────────────────────────────────────
  for (const id of sortedIds) {
    const node = nodeById[id]
    if (!node || node.data.kind !== 'Tool') continue
    const d = node.data
    const varName = pyVar(d.name)
    lines.push(`def ${varName}() -> dict:`)
    lines.push(`    """${d.description || d.name}"""`)
    for (const codeLine of d.code.split('\n')) {
      lines.push(codeLine)
    }
    lines.push('')
  }

  // ── MCP Toolset factories ─────────────────────────────────────────────────
  for (const id of sortedIds) {
    const node = nodeById[id]
    if (!node || node.data.kind !== 'McpToolset') continue
    const d = node.data
    const varName = pyVar(d.name)
    const args = d.args.trim() ? `[${d.args.split(' ').map((a) => `'${a}'`).join(', ')}]` : '[]'
    const filterLine = d.tool_filter.trim()
      ? `,\n    tool_filter=[${d.tool_filter.split(',').map((t) => `'${t.trim()}'`).join(', ')}],`
      : ''
    lines.push(`${varName} = McpToolset(`)
    lines.push(`    connection_params=StdioConnectionParams(`)
    lines.push(`        server_params=StdioServerParameters(`)
    lines.push(`            command='${d.command}',`)
    lines.push(`            args=${args},`)
    lines.push(`        ),`)
    lines.push(`    )${filterLine}`)
    lines.push(`)`)
    lines.push('')
  }

  // ── Agent definitions ─────────────────────────────────────────────────────
  for (const id of sortedIds) {
    const node = nodeById[id]
    if (!node) continue
    const { kind } = node.data
    if (kind === 'Tool' || kind === 'McpToolset') continue

    const isRoot = roots.length === 1 && roots[0].id === id
    const varName = isRoot ? 'root_agent' : pyVar(node.data.name)

    if (kind === 'LlmAgent') {
      const d = node.data
      const toolsList = (agentTools[id] ?? [])
        .map((tid) => pyVar(nodeById[tid]?.data.name ?? tid))
        .join(', ')
      lines.push(`${varName} = LlmAgent(`)
      lines.push(`    model='${d.model}',`)
      lines.push(`    name='${d.name}',`)
      if (d.description) lines.push(`    description='${d.description}',`)
      if (d.output_key) lines.push(`    output_key='${d.output_key}',`)
      if (toolsList) lines.push(`    tools=[${toolsList}],`)
      lines.push(`    instruction=(`)
      for (const instrLine of d.instruction.split('\n')) {
        lines.push(`        '${instrLine.replace(/'/g, "\\'")}'`)
      }
      lines.push(`    ),`)
      lines.push(`)`)
      lines.push('')
    } else if (kind === 'SequentialAgent') {
      const d = node.data
      const children = (subAgentChildren[id] ?? [])
        .map((cid) => {
          const isChildRoot = roots.length === 1 && roots[0].id === cid
          return isChildRoot ? 'root_agent' : pyVar(nodeById[cid]?.data.name ?? cid)
        })
        .join(', ')
      lines.push(`${varName} = SequentialAgent(`)
      lines.push(`    name='${d.name}',`)
      if (d.description) lines.push(`    description='${d.description}',`)
      lines.push(`    sub_agents=[${children}],`)
      lines.push(`)`)
      lines.push('')
    } else if (kind === 'ParallelAgent') {
      const d = node.data
      const children = (subAgentChildren[id] ?? [])
        .map((cid) => pyVar(nodeById[cid]?.data.name ?? cid))
        .join(', ')
      lines.push(`${varName} = ParallelAgent(`)
      lines.push(`    name='${d.name}',`)
      if (d.description) lines.push(`    description='${d.description}',`)
      lines.push(`    sub_agents=[${children}],`)
      lines.push(`)`)
      lines.push('')
    } else if (kind === 'LoopAgent') {
      const d = node.data
      const children = (subAgentChildren[id] ?? [])
        .map((cid) => pyVar(nodeById[cid]?.data.name ?? cid))
        .join(', ')
      lines.push(`${varName} = LoopAgent(`)
      lines.push(`    name='${d.name}',`)
      if (d.description) lines.push(`    description='${d.description}',`)
      lines.push(`    sub_agents=[${children}],`)
      lines.push(`    max_iterations=${d.max_iterations},`)
      lines.push(`)`)
      lines.push('')
    }
  }

  // If multiple roots, comment them all as candidates
  if (roots.length !== 1) {
    lines.push(
      '# WARNING: Could not determine a single root agent.',
    )
    lines.push(
      '# Candidates: ' + roots.map((r) => pyVar(r.data.name)).join(', '),
    )
    if (roots.length > 0) {
      lines.push(`root_agent = ${pyVar(roots[0].data.name)}  # ← pick the correct root`)
    }
  }

  return lines.join('\n')
}
